# Day/Night rutines
- alias: darkness_lights_outside
  trigger:
    platform: state
    entity_id: sun.sun
    to: "sunset"
  action:
    - service: script.turn_on
      entity_id: script.sunset_outside

- alias: darkness_lights_inside
  trigger:
    platform: state
    entity_id: sun.sun
    to: "sunset"
  action:
    - service: script.turn_on
      antity_id: script.sunset_inside

- alias: light
  trigger:
    platform: state
    entity_id: sun.sun
    to: "sunrise"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - group.darkness_lights_outside
          - group.darkness_lights_inside

# Bedtime rutines
- alias: nighty_night
  trigger:
    platform: state
    entity_id: input_boolean.night_time
    to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: group.good_night_group_off
    - service: homeassistant.turn_on
      entity_id: group.good_night_group_on

# Home/Away rutines
- alias: welcome_home
  trigger:
    platform: state
    entity_id: input_boolean.at_home
    to: "on"
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.hall
        - light.lill_hall
        - group.kitchen
  condition:
    - condition: sun
      after: sunset

- alias: see_you_soon
  trigger:
    platform: state
    entity_id: input_boolean.at_home
    to: "off"
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - group.inside
    - service: homeassistant.turn_on
      data_template:
        entity_id: >
          {% if is_state('sun.sun', 'below_horizon') %}
            group.darkness_inside
          {% else%}
            none
          {% endif %}
  condition:
    - condition: sun
      after: sunset

# Morning ruitines
- alias: morning_sunrise_tak
  trigger: 
    platform: time
    at: "06:05:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: script.turn_on
      entity_id: script.sunrise_tak

- alias: morning_sunrise_nattduk
  trigger: 
    platform: time
    at: "06:10:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: script.turn_on
      entity_id: script.sunrise_nattduk

# - alias: morgonrutin
#   trigger: 
#     platform: state
#     entity_id: sensor_binary.hue_motion_sensor_1_motion
#     to: 'on'
#   condition:
#     condition: and
#     conditions:
#       - condition: sun
#         before: sunrise
#       - condition: time
#         before: '07:30:00'
#         after: '05:30:00'
#   action:
#     service: light.turn_on
#     entity_id:
#       - light.hall
#       - light.kok

# Activities
- alias: watch_tv
  trigger:
    platform: state
    entity_id: input_boolean.tv_time
    to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id:
        - group.diningroom
        - group.vardagsrum
        - light.hall
        - light.lill_hall
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.piano
        brightness: 150

