- alias: morgonrutin
  trigger: 
    platform: state
    entity_id: sensor_binary.hue_motion_sensor_1_motion
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: sun
        before: sunrise
      - condition: time
        before: '07:30:00'
        after: '05:30:00'
  action:
    service: light.turn_on
    entity_id:
      - light.hall
      - light.kok
- alias: darkness
  trigger:
    platform: state
    entity_id: sun.sun
    to: "sunset"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: group.nightlights
        brightness: 130
- alias: light
  trigger:
    platform: state
    entity_id: sun.sun
    to: "sunrise"
  action:
    - service: homeassistant.turn_off
      entity_id: light.all
- alias: nighty_night
  trigger:
    platform: state
    entity_id: input_boolean.night_time
    to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: group.good_night_group_off
    - service: homeassistant.turn_on
      entry_id: light.piano
  
