# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#  base_url: skaven133.duckdns.org
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

frontend:

hassio:

config:

sun:

automation: !include_dir_merge_list automation/
script: !include scripts.yaml
group: !include groups.yaml

homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 30
  unit_system: metric
  time_zone: Europe/Stockholm

# Set up devices
hue:
  bridges:
    - host: 192.168.1.37
      allow_hue_groups: false
      allow_unreachable: true

sonos:
  media_player:
    hosts: 
    - 192.168.1.54
    - 192.168.1.171
    - 192.168.1.219
media_player:
  - platform: philips_js
    host: 192.168.1.206
    
tradfri:
  host: 192.168.1.214
  allow_tradfri_groups: false
 


input_boolean:
  at_home:
    name: Someone is at home
    initial: off
    icon: "if (state === 'on') return mdi:account-check; else return mdi:account-remove;"
  night_time:
    name: Good night
    initial: off
    icon: "if (state === 'on') return mdi:sleep; else return mdi:white-balance-sunny;"
  tv_time:
    name: Tv time
    initial: off
  kitchen_dinner:
    name: Kitchen dinner
    initial: off
  dining_dinner:
    name: Dining room dinner
    initial: off
