# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#  base_url: skaven133.duckdns.org
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

frontend:

hassio:

config:


automation: !include automations.yaml
script: !include scripts.yaml
group: !include groups.yaml

homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 30
  unit_system: metric
  time_zone: Europe/Stockholm

# Set up devices
hue:
  bridges:
    - host: 192.168.1.147
      allow_hue_groups: false
      allow_unreachable: true

sonos:
  media_player:
    hosts: 192.168.1.179
    
tradfri:
  host: 192.168.1.229
  allow_tradfri_groups: false

input_boolean:
  adam_home:
    name: Adam is home
    initial: off
    icon: "if (state === 'on') return mdi:account-check; else return mdi:account-remove;"
  hanna_home:
    name: Hanna is home
    initial: off
    icon: "if (state === 'on') return mdi:account-check; else return mdi:account-remove;"
  night_time:
    name: Awake or asleep.
    initial: off
    icon: "if (state === 'on') return mdi:sleep; else return mdi:white-balance-sunny;"

