# Bedtime rutines
- alias: nighty_night
  trigger:
    platform: state
    entity_id: input_boolean.night_time
    to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: group.good_night_group_off
    - service: homeassistant.turn_on
      entity_id: group.good_night_group_on
- alias: good_morning
  trigger:
    platform: state
    entity_id: input_boolean.night_time
    to: "off"
  action:
    - service: homeassistant.turn_off
      data_template:
        entity_id: >
          {% if is_state('sun.sun','above_horizon') %}
            group.bedroom
          {% else %}
            none
          {% endif %}
    - service: homeassistant.turn_on
      data_template:
        entity_id: >
          {% if is_state('sun.sun','below_horizon') %}
            group.darkness_inside
          {% else %}
            none
          {% endif %}

# Home/Away rutines
- alias: welcome_home
  trigger:
    platform: state
    entity_id: input_boolean.at_home
    to: "on"
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.hall
        - light.lill_hall
        - group.kitchen
  condition:
    - condition: sun
      after: sunset

- alias: see_you_soon
  trigger:
    platform: state
    entity_id: input_boolean.at_home
    to: "off"
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - group.inside
    - service: homeassistant.turn_on
      data_template:
        entity_id: >
          {% if is_state('sun.sun','below_horizon') %}
            group.darkness_inside
          {% else %}
            none
          {% endif %}
  condition:
    - condition: sun
      after: sunset

#TV rutines
- alias: watch_tv
  trigger:
    platform: state
    entity_id: input_boolean.tv_time
    to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: group.ground_floor
    - service: homeassistant.turn_on
      data:
        entity_id: light.piano
        brightness: 170
        xy_color: [0.60,0.48]

# Dinner rutines
- alias: dinner_in_kitchen
  trigger:
    platform: state
    entity_id: input_boolean.kitchen_dinner
    to: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: group.ground_floor
    - service: homeassistant.turn_on
      data:
        entity_id: group.kitchen
        brightness: 170
        xy_color: [0.60,0.48]
