# Morning ruitines
- alias: morning_sunrise_tak
  trigger: 
    platform: time
    at: "06:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: script.turn_on
      entity_id: script.sunrise_tak

- alias: morning_sunrise_nattduk
  trigger: 
    platform: time
    at: "06:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: script.turn_on
      entity_id: script.sunrise_nattduk

- alias: reset_good_night
  trigger:
    platform: time
    at: "10:00:00"
  action:
    - service: state.turn_off
      entity_id: input_boolean.night_time
