# Morning ruitines
- alias: morning_sunrise_tak
  trigger: 
    platform: time
    at: "06:50:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: script.turn_on
      entity_id: script.sunrise_tak

- alias: morning_sunrise_nattduk
  trigger: 
    platform: time
    at: "06:55:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: script.turn_on
      entity_id: script.sunrise_nattduk
